### ISSUE TITLE
error in merge_barcode_files_10x

### ISSUE THREAD

**Issue by cheesemania** [pachterlab/sircel#13]
Hi, I'm getting an error in processing 10X data

~/./sircel/sircel/sircel --10xgenomics \
--barcodes  R1.fastq.gz \
--umis I1.fastq.gz \
--reads R2.fastq.gz \
--output_dir ~/10x_out --kallisto_idx kallisto_ref.idx

Inspecting and pre-processing inputs
Unzipping and merging files (temporary)
Traceback (most recent call last):
  File "/home/ian/./sircel/sircel/sircel", line 9, in <module>
    load_entry_point('sircel==0.1.2', 'console_scripts', 'sircel')()
  File "/usr/local/lib/python3.5/dist-packages/sircel-0.1.2-py3.5.egg/sircel/__main__.py", line 5, in main
    output_files = run_all(args)
  File "/usr/local/lib/python3.5/dist-packages/sircel-0.1.2-py3.5.egg/sircel/Sircel_master.py", line 67, in run_all
    args['umis'].split(','))
  File "/usr/local/lib/python3.5/dist-packages/sircel-0.1.2-py3.5.egg/sircel/utils/IO_utils.py", line 213, in merge_barcodefiles_10x
    ('\n'.join(umis), '\n'.join(cells))	
NameError: name 'umis' is not defined

It looked like the   ('\n'.join(umis), '\n'.join(cells))	 part had undefined elements, I recompiled changing 'umis' to 'umi' and 'cells' to 'bc', and got a new error

Inspecting and pre-processing inputs
Unzipping and merging files (temporary)
Traceback (most recent call last):
  File "/home/ian/./sircel/sircel/sircel", line 9, in <module>
    load_entry_point('sircel==0.1.2', 'console_scripts', 'sircel')()
  File "/usr/local/lib/python3.5/dist-packages/sircel-0.1.2-py3.5.egg/sircel/__main__.py", line 5, in main
    output_files = run_all(args)
  File "/usr/local/lib/python3.5/dist-packages/sircel-0.1.2-py3.5.egg/sircel/Sircel_master.py", line 67, in run_all
    args['umis'].split(','))
  File "/usr/local/lib/python3.5/dist-packages/sircel-0.1.2-py3.5.egg/sircel/utils/IO_utils.py", line 213, in merge_barcodefiles_10x
    ('\n'.join(umi), '\n'.join(bc))	
AssertionError: Reads are not in order
m
i
h
c
5
h
m
_

Though admittedly this second one may be due to me mangling your code

Any suggestions on what may be going wrong?

Thanks,

Ian

**Comment by modash** [comment]
Hi,

I am also facing the same issue. I have noticed few patch works have been done previously on this, but still getting this error. Any idea?

--
Ashick

**Comment by kuikuisven** [comment]
Hi , I also get the same error..
