### ISSUE TITLE
Improve Installation Documentation

### ISSUE THREAD

**Issue by marcc-hpc** [pachterlab/sircel#16]
Hi,

Working with a user here using your software.  

I think if would benefit if you provide users with an end-to-end installation example running with Anaconda:

I've worked on a solution that does that here and would be happy to incorporate this into your documentation

https://gist.github.com/marcc-hpc/b15236cf569336d29947854d88e81ae2

Kevin from MARCC (www.marcc.jhu.edu)

**Comment by cgirardot** [comment]
same here, after install execution fails due to redis missing. 

/sircel/sircel 
Traceback (most recent call last):
  File "./sircel/sircel", line 11, in <module>
    load_entry_point('sircel==0.1.2', 'console_scripts', 'sircel')()
  File "/g/funcgen/gbcs/public/software/conda/envs/sircel_25042019/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/g/funcgen/gbcs/public/software/conda/envs/sircel_25042019/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/g/funcgen/gbcs/public/software/conda/envs/sircel_25042019/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/g/funcgen/gbcs/public/software/conda/envs/sircel_25042019/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/g/funcgen/gbcs/public/software/conda/envs/sircel_25042019/lib/python3.7/site-packages/sircel-0.1.2-py3.7.egg/sircel/__init__.py", line 1, in <module>
    from sircel.Sircel_master import get_args, run_all
  File "/g/funcgen/gbcs/public/software/conda/envs/sircel_25042019/lib/python3.7/site-packages/sircel-0.1.2-py3.7.egg/sircel/Sircel_master.py", line 7, in <module>
    from sircel.utils import IO_utils, Plot_utils
  File "/g/funcgen/gbcs/public/software/conda/envs/sircel_25042019/lib/python3.7/site-packages/sircel-0.1.2-py3.7.egg/sircel/utils/__init__.py", line 2, in <module>
    from sircel.utils.IO_utils import *
  File "/g/funcgen/gbcs/public/software/conda/envs/sircel_25042019/lib/python3.7/site-packages/sircel-0.1.2-py3.7.egg/sircel/utils/IO_utils.py", line 13, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
