### ISSUE TITLE
running kallisto failed

### ISSUE THREAD

**Issue by doublehelixlf** [pachterlab/sircel#9]
Reads_split worked well. But kallisto failed to execute. Error message is below.

Flushing assignments index
Split reads. Time elapsed 230.84725165367126 seconds

Running kallisto
Traceback (most recent call last):
  File "/home/feng/anaconda3/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/feng/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/feng/anaconda3/lib/python3.5/site-packages/sircel-0.1-py3.5.egg/sircel/__main__.py", line 4, in <module>
    output_files = run_all(args)
  File "/home/feng/anaconda3/lib/python3.5/site-packages/sircel-0.1-py3.5.egg/sircel/Sircel_master.py", line 101, in run_all
    output_files)
  File "/home/feng/anaconda3/lib/python3.5/site-packages/sircel-0.1-py3.5.egg/sircel/Sircel_master.py", line 129, in run_kallisto
    '-i', 		args['kallisto_idx'],
NameError: name 'args' is not defined

**Comment by ahy1221** [comment]
Yes, I also meet this problem right now. Another question is that can we just only run the kallisto step after fixing this bug ?

**Comment by doublehelixlf** [comment]
BTW, there was no problem running kallisto with an earlier version of Sircel. Hope the author could add an option of running kallisto only.

**Comment by axtambe** [comment]
Sorry everyone. Problem is now fixed
